// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError('DefaultFirebaseOptions are not supported for this platform.');
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAeQJEXbQ_g1sNmNViL0BTXCdlPLvOhtYQ',
    appId: '1:196481842697:web:dd9cab615321773ad002d8',
    messagingSenderId: '196481842697',
    projectId: 'vibe-flutter-ai-sidekick',
    authDomain: 'vibe-flutter-ai-sidekick.firebaseapp.com',
    storageBucket: 'vibe-flutter-ai-sidekick.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOcwk1C338IK9dOuJqO7-FsAr34746P7Q',
    appId: '1:196481842697:android:f405054f84809c0bd002d8',
    messagingSenderId: '196481842697',
    projectId: 'vibe-flutter-ai-sidekick',
    storageBucket: 'vibe-flutter-ai-sidekick.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDGoeR7XlQOxzp80EiQgnG3SXquOYwg5Q',
    appId: '1:196481842697:ios:08b54da6edbe0f62d002d8',
    messagingSenderId: '196481842697',
    projectId: 'vibe-flutter-ai-sidekick',
    storageBucket: 'vibe-flutter-ai-sidekick.firebasestorage.app',
    iosBundleId: 'hu.sidekick.app',
  );
}
